const METRO_AREAS = [
	{ metroName: "Akron", state: "Ohio"},
	{ metroName: "Albany-Schenectady-Troy", state: "New York"},
	{ metroName: "Albuquerque", state: "New Mexico"},
	{ metroName: "Allentown-Bethlehem-Easton", state: "Pennsylvania-New Jersey"},
	{ metroName: "Allentown-Bethlehem-Easton", state: "Pennsylvania-New Jersey"},
	{ metroName: "Amarillo", state: "Texas"},
	{ metroName: "Anchorage", state: "Alaska"},
	{ metroName: "Ann Arbor", state: "Michigan"},
	{ metroName: "Appleton", state: "Wisconsin"},
	{ metroName: "Asheville", state: "North Carolina"},
	{ metroName: "Athens-Clarke County", state: "Georgia"},
	{ metroName: "Atlanta-Sandy Springs-Marietta", state: "Georgia"},
	{ metroName: "Atlantic City-Hammonton", state: "New Jersey"},
	{ metroName: "Augusta-Richmond County", state: "Georgia-South Carolina"},
	{ metroName: "Augusta-Richmond County", state: "Georgia-South Carolina"},
	{ metroName: "Austin-Round Rock-San Marcos", state: "Texas"},
	{ metroName: "Bakersfield-Delano", state: "California"},
	{ metroName: "Baltimore-Towson", state: "Maryland"},
	{ metroName: "Barnstable Town", state: "Massachusetts"},
	{ metroName: "Baton Rouge", state: "Louisiana"},
	{ metroName: "Beaumont-Port Arthur", state: "Texas"},
	{ metroName: "Bellingham", state: "Washington"},
	{ metroName: "Binghamton", state: "New York"},
	{ metroName: "Birmingham-Hoover", state: "Alabama"},
	{ metroName: "Boise City-Nampa", state: "Idaho"},
	{ metroName: "Boston-Cambridge-Quincy", state: "Massachusetts-New Hampshire"},
	{ metroName: "Boston-Cambridge-Quincy", state: "Massachusetts-New Hampshire"},
	{ metroName: "Boulder", state: "Colorado"},
	{ metroName: "Bremerton-Silverdale", state: "Washington"},
	{ metroName: "Bridgeport-Stamford-Norwalk", state: "Connecticut"},
	{ metroName: "Brownsville-Harlingen", state: "Texas"},
	{ metroName: "Buffalo-Niagara Falls", state: "New York"},
	{ metroName: "Burlington-South Burlington", state: "Vermont"},
	{ metroName: "Canton-Massillon", state: "Ohio"},
	{ metroName: "Cape Coral-Fort Myers", state: "Florida"},
	{ metroName: "Cedar Rapids", state: "Iowa"},
	{ metroName: "Champaign-Urbana", state: "Illinois"},
	{ metroName: "Charleston-North Charleston-Summerville", state: "South Carolina"},
	{ metroName: "Charleston", state: "West Virginia"},
	{ metroName: "Charlotte-Gastonia-Rock Hill", state: "North Carolina-South Carolina"},
	{ metroName: "Charlotte-Gastonia-Rock Hill", state: "North Carolina-South Carolina"},
	{ metroName: "Charlottesville", state: "Virginia"},
	{ metroName: "Chattanooga", state: "Tennessee-Georgia"},
	{ metroName: "Chattanooga", state: "Tennessee-Georgia"},
	{ metroName: "Chicago-Joliet-Naperville", state: "Illinois-Indiana-Wisconsin"},
	{ metroName: "Chicago-Joliet-Naperville", state: "Illinois-Indiana-Wisconsin"},
	{ metroName: "Chicago-Joliet-Naperville", state: "Illinois-Indiana-Wisconsin"},
	{ metroName: "Chico", state: "California"},
	{ metroName: "Cincinnati-Middletown", state: "Ohio-Kentucky-Indiana"},
	{ metroName: "Cincinnati-Middletown", state: "Ohio-Kentucky-Indiana"},
	{ metroName: "Cincinnati-Middletown", state: "Ohio-Kentucky-Indiana"},
	{ metroName: "Clarksville", state: "Tennessee-Kentucky"},
	{ metroName: "Clarksville", state: "Tennessee-Kentucky"},
	{ metroName: "Cleveland-Elyria-Mentor", state: "Ohio"},
	{ metroName: "College Station-Bryan", state: "Texas"},
	{ metroName: "Colorado Springs", state: "Colorado"},
	{ metroName: "Columbia", state: "South Carolina"},
	{ metroName: "Columbus", state: "Georgia-Alabama"},
	{ metroName: "Columbus", state: "Georgia-Alabama"},
	{ metroName: "Columbus", state: "Ohio"},
	{ metroName: "Corpus Christi", state: "Texas"},
	{ metroName: "Crestview-Fort Walton Beach-Destin", state: "Florida"},
	{ metroName: "Dallas-Fort Worth-Arlington", state: "Texas"},
	{ metroName: "Daphne-Fairhope-Foley", state: "Alabama Micropolitan Statistical Area"},
	{ metroName: "Davenport-Moline-Rock Island", state: "Iowa-Illinois"},
	{ metroName: "Davenport-Moline-Rock Island", state: "Iowa-Illinois"},
	{ metroName: "Dayton", state: "Ohio"},
	{ metroName: "Deltona-Daytona Beach-Ormond Beach", state: "Florida"},
	{ metroName: "Denver-Aurora-Broomfield", state: "Colorado"},
	{ metroName: "Des Moines-West Des Moines", state: "Iowa"},
	{ metroName: "Detroit-Warren-Livonia", state: "Michigan"},
	{ metroName: "Duluth", state: "Minnesota-Wisconsin"},
	{ metroName: "Duluth", state: "Minnesota-Wisconsin"},
	{ metroName: "Durham-Chapel Hill", state: "North Carolina"},
	{ metroName: "El Paso", state: "Texas"},
	{ metroName: "Elkhart-Goshen", state: "Indiana"},
	{ metroName: "Erie", state: "Pennsylvania"},
	{ metroName: "Eugene-Springfield", state: "Oregon"},
	{ metroName: "Evansville", state: "Indiana-Kentucky"},
	{ metroName: "Evansville", state: "Indiana-Kentucky"},
	{ metroName: "Fargo", state: "North Dakota-Minnesota"},
	{ metroName: "Fargo", state: "North Dakota-Minnesota"},
	{ metroName: "Fayetteville-Springdale-Rogers", state: "Arkansas-Missouri"},
	{ metroName: "Fayetteville-Springdale-Rogers", state: "Arkansas-Missouri"},
	{ metroName: "Fayetteville", state: "North Carolina"},
	{ metroName: "Flint", state: "Michigan"},
	{ metroName: "Florence", state: "South Carolina"},
	{ metroName: "Fort Collins-Loveland", state: "Colorado"},
	{ metroName: "Fort Smith", state: "Arkansas-Oklahoma"},
	{ metroName: "Fort Smith", state: "Arkansas-Oklahoma"},
	{ metroName: "Fort Wayne", state: "Indiana"},
	{ metroName: "Fresno", state: "California"},
	{ metroName: "Gainesville", state: "Florida"},
	{ metroName: "Grand Rapids-Wyoming", state: "Michigan"},
	{ metroName: "Greeley", state: "Colorado"},
	{ metroName: "Green Bay", state: "Wisconsin"},
	{ metroName: "Greensboro-High Point", state: "North Carolina"},
	{ metroName: "Greenville-Mauldin-Easley", state: "South Carolina"},
	{ metroName: "Gulfport-Biloxi", state: "Mississippi"},
	{ metroName: "Hagerstown-Martinsburg", state: "Maryland-West Virginia"},
	{ metroName: "Hagerstown-Martinsburg", state: "Maryland-West Virginia"},
	{ metroName: "Harrisburg-Carlisle", state: "Pennsylvania"},
	{ metroName: "Hartford-West Hartford-East Hartford", state: "Connecticut"},
	{ metroName: "Hickory-Lenoir-Morganton", state: "North Carolina"},
	{ metroName: "Hilton Head Island-Beaufort", state: "South Carolina Micropolitan Statistical Area"},
	{ metroName: "Holland-Grand Haven", state: "Michigan"},
	{ metroName: "Honolulu", state: "Hawaii"},
	{ metroName: "Houma-Bayou Cane-Thibodaux", state: "Louisiana"},
	{ metroName: "Houston-Sugar Land-Baytown", state: "Texas"},
	{ metroName: "Huntington-Ashland", state: "West Virginia-Kentucky-Ohio"},
	{ metroName: "Huntington-Ashland", state: "West Virginia-Kentucky-Ohio"},
	{ metroName: "Huntington-Ashland", state: "West Virginia-Kentucky-Ohio"},
	{ metroName: "Huntsville", state: "Alabama"},
	{ metroName: "Indianapolis-Carmel", state: "Indiana"},
	{ metroName: "Jackson", state: "Mississippi"},
	{ metroName: "Jacksonville", state: "Florida"},
	{ metroName: "Johnson City", state: "Tennessee"},
	{ metroName: "Kalamazoo-Portage", state: "Michigan"},
	{ metroName: "Kansas City", state: "Missouri-Kansas"},
	{ metroName: "Kansas City", state: "Missouri-Kansas"},
	{ metroName: "Kennewick-Pasco-Richland", state: "Washington"},
	{ metroName: "Killeen-Temple-Fort Hood", state: "Texas"},
	{ metroName: "Kingsport-Bristol-Bristol", state: "Tennessee-Virginia"},
	{ metroName: "Kingsport-Bristol-Bristol", state: "Tennessee-Virginia"},
	{ metroName: "Knoxville", state: "Tennessee"},
	{ metroName: "Lafayette", state: "Indiana"},
	{ metroName: "Lafayette", state: "Louisiana"},
	{ metroName: "Lake Charles", state: "Louisiana"},
	{ metroName: "Lake Havasu City-Kingman", state: "Arizona"},
	{ metroName: "Lakeland-Winter Haven", state: "Florida"},
	{ metroName: "Lancaster", state: "Pennsylvania"},
	{ metroName: "Lansing-East Lansing", state: "Michigan"},
	{ metroName: "Laredo", state: "Texas"},
	{ metroName: "Las Cruces", state: "New Mexico"},
	{ metroName: "Las Vegas-Paradise", state: "Nevada"},
	{ metroName: "Lexington-Fayette", state: "Kentucky"},
	{ metroName: "Lincoln", state: "Nebraska"},
	{ metroName: "Little Rock-North Little Rock-Conway", state: "Arkansas"},
	{ metroName: "Longview", state: "Texas"},
	{ metroName: "Los Angeles-Long Beach-Santa Ana", state: "California"},
	{ metroName: "Louisville/Jefferson County", state: "Kentucky-Indiana"},
	{ metroName: "Louisville/Jefferson County", state: "Kentucky-Indiana"},
	{ metroName: "Lubbock", state: "Texas"},
	{ metroName: "Lynchburg", state: "Virginia"},
	{ metroName: "Macon", state: "Georgia"},
	{ metroName: "Madison", state: "Wisconsin"},
	{ metroName: "Manchester-Nashua", state: "New Hampshire"},
	{ metroName: "McAllen-Edinburg-Mission", state: "Texas"},
	{ metroName: "Medford", state: "Oregon"},
	{ metroName: "Memphis", state: "Tennessee-Mississippi-Arkansas"},
	{ metroName: "Memphis", state: "Tennessee-Mississippi-Arkansas"},
	{ metroName: "Memphis", state: "Tennessee-Mississippi-Arkansas"},
	{ metroName: "Merced", state: "California"},
	{ metroName: "Miami-Fort Lauderdale-Pompano Beach", state: "Florida"},
	{ metroName: "Milwaukee-Waukesha-West Allis", state: "Wisconsin"},
	{ metroName: "Minneapolis-St. Paul-Bloomington", state: "Minnesota-Wisconsin"},
	{ metroName: "Minneapolis-St. Paul-Bloomington", state: "Minnesota-Wisconsin"},
	{ metroName: "Mobile", state: "Alabama"},
	{ metroName: "Modesto", state: "California"},
	{ metroName: "Montgomery", state: "Alabama"},
	{ metroName: "Myrtle Beach-North Myrtle Beach-Conway", state: "South Carolina"},
	{ metroName: "Naples-Marco Island", state: "Florida"},
	{ metroName: "Nashville-Davidson--Murfreesboro--Franklin", state: "Tennessee"},
	{ metroName: "New Haven-Milford", state: "Connecticut"},
	{ metroName: "New Orleans-Metairie-Kenner", state: "Louisiana"},
	{ metroName: "New York-Northern New Jersey-Long Island", state: "New York-New Jersey-Pennsylvania"},
	{ metroName: "New York-Northern New Jersey-Long Island", state: "New York-New Jersey-Pennsylvania"},
	{ metroName: "New York-Northern New Jersey-Long Island", state: "New York-New Jersey-Pennsylvania"},
	{ metroName: "North Port-Bradenton-Sarasota", state: "Florida"},
	{ metroName: "Norwich-New London", state: "Connecticut"},
	{ metroName: "Ocala", state: "Florida"},
	{ metroName: "Ogden-Clearfield", state: "Utah"},
	{ metroName: "Oklahoma City", state: "Oklahoma"},
	{ metroName: "Olympia", state: "Washington"},
	{ metroName: "Omaha-Council Bluffs", state: "Nebraska-Iowa"},
	{ metroName: "Omaha-Council Bluffs", state: "Nebraska-Iowa"},
	{ metroName: "Orlando-Kissimmee-Sanford", state: "Florida"},
	{ metroName: "Oxnard-Thousand Oaks-Ventura", state: "California"},
	{ metroName: "Palm Bay-Melbourne-Titusville", state: "Florida"},
	{ metroName: "Pensacola-Ferry Pass-Brent", state: "Florida"},
	{ metroName: "Peoria", state: "Illinois"},
	{ metroName: "Philadelphia-Camden-Wilmington", state: "Pennsylvania-New Jersey-Delaware-Maryland"},
	{ metroName: "Philadelphia-Camden-Wilmington", state: "Pennsylvania-New Jersey-Delaware-Maryland"},
	{ metroName: "Philadelphia-Camden-Wilmington", state: "Pennsylvania-New Jersey-Delaware-Maryland"},
	{ metroName: "Philadelphia-Camden-Wilmington", state: "Pennsylvania-New Jersey-Delaware-Maryland"},
	{ metroName: "Phoenix-Mesa-Glendale", state: "Arizona"},
	{ metroName: "Pittsburgh", state: "Pennsylvania"},
	{ metroName: "Port St. Lucie", state: "Florida"},
	{ metroName: "Portland-South Portland-Biddeford", state: "Maine"},
	{ metroName: "Portland-Vancouver-Hillsboro", state: "Oregon-Washington"},
	{ metroName: "Portland-Vancouver-Hillsboro", state: "Oregon-Washington"},
	{ metroName: "Poughkeepsie-Newburgh-Middletown", state: "New York"},
	{ metroName: "Prescott", state: "Arizona"},
	{ metroName: "Providence-New Bedford-Fall River", state: "Rhode Island-Massachusetts"},
	{ metroName: "Providence-New Bedford-Fall River", state: "Rhode Island-Massachusetts"},
	{ metroName: "Provo-Orem", state: "Utah"},
	{ metroName: "Raleigh-Cary", state: "North Carolina"},
	{ metroName: "Reading", state: "Pennsylvania"},
	{ metroName: "Reno-Sparks", state: "Nevada"},
	{ metroName: "Richmond", state: "Virginia"},
	{ metroName: "Riverside-San Bernardino-Ontario", state: "California"},
	{ metroName: "Roanoke", state: "Virginia"},
	{ metroName: "Rochester", state: "New York"},
	{ metroName: "Rockford", state: "Illinois"},
	{ metroName: "Sacramento--Arden-Arcade--Roseville", state: "California"},
	{ metroName: "Salem", state: "Oregon"},
	{ metroName: "Salinas", state: "California"},
	{ metroName: "Salt Lake City", state: "Utah"},
	{ metroName: "San Antonio-New Braunfels", state: "Texas"},
	{ metroName: "San Diego-Carlsbad-San Marcos", state: "California"},
	{ metroName: "San Francisco-Oakland-Fremont", state: "California"},
	{ metroName: "San Jose-Sunnyvale-Santa Clara", state: "California"},
	{ metroName: "San Luis Obispo-Paso Robles", state: "California"},
	{ metroName: "Santa Barbara-Santa Maria-Goleta", state: "California"},
	{ metroName: "Santa Cruz-Watsonville", state: "California"},
	{ metroName: "Santa Rosa-Petaluma", state: "California"},
	{ metroName: "Savannah", state: "Georgia"},
	{ metroName: "Scranton--Wilkes-Barre", state: "Pennsylvania"},
	{ metroName: "Seaford", state: "Delaware Micropolitan Statistical Area"},
	{ metroName: "Seattle-Tacoma-Bellevue", state: "Washington"},
	{ metroName: "Shreveport-Bossier City", state: "Louisiana"},
	{ metroName: "Sioux Falls", state: "South Dakota"},
	{ metroName: "South Bend-Mishawaka", state: "Indiana-Michigan"},
	{ metroName: "South Bend-Mishawaka", state: "Indiana-Michigan"},
	{ metroName: "Spartanburg", state: "South Carolina"},
	{ metroName: "Spokane", state: "Washington"},
	{ metroName: "Springfield", state: "Illinois"},
	{ metroName: "Springfield", state: "Massachusetts"},
	{ metroName: "Springfield", state: "Missouri"},
	{ metroName: "St. Cloud", state: "Minnesota"},
	{ metroName: "St. Louis", state: "Missouri-Illinois"},
	{ metroName: "St. Louis", state: "Missouri-Illinois"},
	{ metroName: "Stockton", state: "California"},
	{ metroName: "Syracuse", state: "New York"},
	{ metroName: "Tallahassee", state: "Florida"},
	{ metroName: "Tampa-St. Petersburg-Clearwater", state: "Florida"},
	{ metroName: "Toledo", state: "Ohio"},
	{ metroName: "Topeka", state: "Kansas"},
	{ metroName: "Trenton-Ewing", state: "New Jersey"},
	{ metroName: "Tucson", state: "Arizona"},
	{ metroName: "Tulsa", state: "Oklahoma"},
	{ metroName: "Tuscaloosa", state: "Alabama"},
	{ metroName: "Tyler", state: "Texas"},
	{ metroName: "Utica-Rome", state: "New York"},
	{ metroName: "Vallejo-Fairfield", state: "California"},
	{ metroName: "Virginia Beach-Norfolk-Newport News", state: "Virginia-North Carolina"},
	{ metroName: "Virginia Beach-Norfolk-Newport News", state: "Virginia-North Carolina"},
	{ metroName: "Visalia-Porterville", state: "California"},
	{ metroName: "Waco", state: "Texas"},
	{ metroName: "Washington-Arlington-Alexandria", state: "Washington DC-Virginia-Maryland-West Virginia"},
	{ metroName: "Washington-Arlington-Alexandria", state: "Washington DC-Virginia-Maryland-West Virginia"},
	{ metroName: "Washington-Arlington-Alexandria", state: "Washington DC-Virginia-Maryland-West Virginia"},
	{ metroName: "Washington-Arlington-Alexandria", state: "Washington DC-Virginia-Maryland-West Virginia"},
	{ metroName: "Wichita", state: "Kansas"},
	{ metroName: "Wilmington", state: "North Carolina"},
	{ metroName: "Winston-Salem", state: "North Carolina"},
	{ metroName: "Worcester", state: "Massachusetts"},
	{ metroName: "Yakima", state: "Washington"},
	{ metroName: "York-Hanover", state: "Pennsylvania"},
	{ metroName: "Youngstown-Warren-Boardman", state: "Ohio-Pennsylvania"},
	{ metroName: "Youngstown-Warren-Boardman", state: "Ohio-Pennsylvania"},
	{ metroName: "Yuma", state: "Arizona"},
]

const STATE_NAMES = {
	AL: "Alabama",
	AK: "Alaska",
	AZ: "Arizona",
	AR: "Arkansas",
	CA: "California",
	CO: "Colorado",
	CT: "Connecticut",
	DC: "Washington DC",
	DE: "Delaware",
	FL: "Florida",
	GA: "Georgia",
	HI: "Hawaii",
	ID: "Idaho",
	IL: "Illinois",
	IN: "Indiana",
	IA: "Iowa",
	KS: "Kansas",
	KY: "Kentucky",
	LA: "Louisiana",
	ME: "Maine",
	MD: "Maryland",
	MA: "Massachusetts",
	MI: "Michigan",
	MN: "Minnesota",
	MS: "Mississippi",
	MO: "Missouri",
	MT: "Montana",
	NE: "Nebraska",
	NV: "Nevada",
	NH: "New Hampshire",
	NJ: "New Jersey",
	NM: "New Mexico",
	NY: "New York",
	NC: "North Carolina",
	ND: "North Dakota",
	OH: "Ohio",
	OK: "Oklahoma",
	OR: "Oregon",
	PA: "Pennsylvania",
	RI: "Rhode Island",
	SC: "South Carolina",
	SD: "South Dakota",
	TN: "Tennessee",
	TX: "Texas",
	UT: "Utah",
	VT: "Vermont",
	VA: "Virginia",
	WA: "Washington",
	WV: "West Virginia",
	WI: "Wisconsin",
	WY: "Wyoming",

	// edge cases
	"SC Micropolitan Statistical Area": "South Carolina",
	"DE Micropolitan Statistical Area": "Delaware",
	"AL Micropolitan Statistical Area": "Alabama",
}

module.exports = {
	METRO_AREAS,
	STATE_NAMES,
}