const METRO_AREAS = [
	{ city: "Akron", state: "Ohio", metroAreaName: "Akron, Ohio"},
	{ city: "Albany-Schenectady-Troy", state: "New York", metroAreaName: "Albany-Schenectady-Troy, New York"},
	{ city: "Albuquerque", state: "New Mexico", metroAreaName: "Albuquerque, New Mexico"},
	{ city: "Allentown-Bethlehem-Easton", state: "Pennsylvania-New Jersey", metroAreaName: "Allentown-Bethlehem-Easton, Pennsylvania-New Jersey"},
	{ city: "Amarillo", state: "Texas", metroAreaName: "Amarillo, Texas"},
	{ city: "Anchorage", state: "Alaska", metroAreaName: "Anchorage, Alaska"},
	{ city: "Ann Arbor", state: "Michigan", metroAreaName: "Ann Arbor, Michigan"},
	{ city: "Appleton", state: "Wisconsin", metroAreaName: "Appleton, Wisconsin"},
	{ city: "Asheville", state: "North Carolina", metroAreaName: "Asheville, North Carolina"},
	{ city: "Athens-Clarke County", state: "Georgia", metroAreaName: "Athens-Clarke County, Georgia"},
	{ city: "Atlanta-Sandy Springs-Marietta", state: "Georgia", metroAreaName: "Atlanta-Sandy Springs-Marietta, Georgia"},
	{ city: "Atlantic City-Hammonton", state: "New Jersey", metroAreaName: "Atlantic City-Hammonton, New Jersey"},
	{ city: "Augusta-Richmond County", state: "Georgia-South Carolina", metroAreaName: "Augusta-Richmond County, Georgia-South Carolina"},
	{ city: "Austin-Round Rock-San Marcos", state: "Texas", metroAreaName: "Austin-Round Rock-San Marcos, Texas"},
	{ city: "Bakersfield-Delano", state: "California", metroAreaName: "Bakersfield-Delano, California"},
	{ city: "Baltimore-Towson", state: "Maryland", metroAreaName: "Baltimore-Towson, Maryland"},
	{ city: "Barnstable Town", state: "Massachusetts", metroAreaName: "Barnstable Town, Massachusetts"},
	{ city: "Baton Rouge", state: "Louisiana", metroAreaName: "Baton Rouge, Louisiana"},
	{ city: "Beaumont-Port Arthur", state: "Texas", metroAreaName: "Beaumont-Port Arthur, Texas"},
	{ city: "Bellingham", state: "Washington", metroAreaName: "Bellingham, Washington"},
	{ city: "Binghamton", state: "New York", metroAreaName: "Binghamton, New York"},
	{ city: "Birmingham-Hoover", state: "Alabama", metroAreaName: "Birmingham-Hoover, Alabama"},
	{ city: "Boise City-Nampa", state: "Idaho", metroAreaName: "Boise City-Nampa, Idaho"},
	{ city: "Boston-Cambridge-Quincy", state: "Massachusetts-New Hampshire", metroAreaName: "Boston-Cambridge-Quincy, Massachusetts-New Hampshire"},
	{ city: "Boulder", state: "Colorado", metroAreaName: "Boulder, Colorado"},
	{ city: "Bremerton-Silverdale", state: "Washington", metroAreaName: "Bremerton-Silverdale, Washington"},
	{ city: "Bridgeport-Stamford-Norwalk", state: "Connecticut", metroAreaName: "Bridgeport-Stamford-Norwalk, Connecticut"},
	{ city: "Brownsville-Harlingen", state: "Texas", metroAreaName: "Brownsville-Harlingen, Texas"},
	{ city: "Buffalo-Niagara Falls", state: "New York", metroAreaName: "Buffalo-Niagara Falls, New York"},
	{ city: "Burlington-South Burlington", state: "Vermont", metroAreaName: "Burlington-South Burlington, Vermont"},
	{ city: "Canton-Massillon", state: "Ohio", metroAreaName: "Canton-Massillon, Ohio"},
	{ city: "Cape Coral-Fort Myers", state: "Florida", metroAreaName: "Cape Coral-Fort Myers, Florida"},
	{ city: "Cedar Rapids", state: "Iowa", metroAreaName: "Cedar Rapids, Iowa"},
	{ city: "Champaign-Urbana", state: "Illinois", metroAreaName: "Champaign-Urbana, Illinois"},
	{ city: "Charleston-North Charleston-Summerville", state: "South Carolina", metroAreaName: "Charleston-North Charleston-Summerville, South Carolina"},
	{ city: "Charleston", state: "West Virginia", metroAreaName: "Charleston, West Virginia"},
	{ city: "Charlotte-Gastonia-Rock Hill", state: "North Carolina-South Carolina", metroAreaName: "Charlotte-Gastonia-Rock Hill, North Carolina-South Carolina"},
	{ city: "Charlottesville", state: "Virginia", metroAreaName: "Charlottesville, Virginia"},
	{ city: "Chattanooga", state: "Tennessee-Georgia", metroAreaName: "Chattanooga, Tennessee-Georgia"},
	{ city: "Chicago-Joliet-Naperville", state: "Illinois-Indiana-Wisconsin", metroAreaName: "Chicago-Joliet-Naperville, Illinois-Indiana-Wisconsin"},
	{ city: "Chico", state: "California", metroAreaName: "Chico, California"},
	{ city: "Cincinnati-Middletown", state: "Ohio-Kentucky-Indiana", metroAreaName: "Cincinnati-Middletown, Ohio-Kentucky-Indiana"},
	{ city: "Clarksville", state: "Tennessee-Kentucky", metroAreaName: "Clarksville, Tennessee-Kentucky"},
	{ city: "Cleveland-Elyria-Mentor", state: "Ohio", metroAreaName: "Cleveland-Elyria-Mentor, Ohio"},
	{ city: "College Station-Bryan", state: "Texas", metroAreaName: "College Station-Bryan, Texas"},
	{ city: "Colorado Springs", state: "Colorado", metroAreaName: "Colorado Springs, Colorado"},
	{ city: "Columbia", state: "South Carolina", metroAreaName: "Columbia, South Carolina"},
	{ city: "Columbus", state: "Georgia-Alabama", metroAreaName: "Columbus, Georgia-Alabama"},
	{ city: "Columbus", state: "Ohio", metroAreaName: "Columbus, Ohio"},
	{ city: "Corpus Christi", state: "Texas", metroAreaName: "Corpus Christi, Texas"},
	{ city: "Crestview-Fort Walton Beach-Destin", state: "Florida", metroAreaName: "Crestview-Fort Walton Beach-Destin, Florida"},
	{ city: "Dallas-Fort Worth-Arlington", state: "Texas", metroAreaName: "Dallas-Fort Worth-Arlington, Texas"},
	{ city: "Daphne-Fairhope-Foley", state: "Alabama", metroAreaName: "Daphne-Fairhope-Foley, Alabama"},
	{ city: "Davenport-Moline-Rock Island", state: "Iowa-Illinois", metroAreaName: "Davenport-Moline-Rock Island, Iowa-Illinois"},
	{ city: "Dayton", state: "Ohio", metroAreaName: "Dayton, Ohio"},
	{ city: "Deltona-Daytona Beach-Ormond Beach", state: "Florida", metroAreaName: "Deltona-Daytona Beach-Ormond Beach, Florida"},
	{ city: "Denver-Aurora-Broomfield", state: "Colorado", metroAreaName: "Denver-Aurora-Broomfield, Colorado"},
	{ city: "Des Moines-West Des Moines", state: "Iowa", metroAreaName: "Des Moines-West Des Moines, Iowa"},
	{ city: "Detroit-Warren-Livonia", state: "Michigan", metroAreaName: "Detroit-Warren-Livonia, Michigan"},
	{ city: "Duluth", state: "Minnesota-Wisconsin", metroAreaName: "Duluth, Minnesota-Wisconsin"},
	{ city: "Durham-Chapel Hill", state: "North Carolina", metroAreaName: "Durham-Chapel Hill, North Carolina"},
	{ city: "El Paso", state: "Texas", metroAreaName: "El Paso, Texas"},
	{ city: "Elkhart-Goshen", state: "Indiana", metroAreaName: "Elkhart-Goshen, Indiana"},
	{ city: "Erie", state: "Pennsylvania", metroAreaName: "Erie, Pennsylvania"},
	{ city: "Eugene-Springfield", state: "Oregon", metroAreaName: "Eugene-Springfield, Oregon"},
	{ city: "Evansville", state: "Indiana-Kentucky", metroAreaName: "Evansville, Indiana-Kentucky"},
	{ city: "Fargo", state: "North Dakota-Minnesota", metroAreaName: "Fargo, North Dakota-Minnesota"},
	{ city: "Fayetteville-Springdale-Rogers", state: "Arkansas-Missouri", metroAreaName: "Fayetteville-Springdale-Rogers, Arkansas-Missouri"},
	{ city: "Fayetteville", state: "North Carolina", metroAreaName: "Fayetteville, North Carolina"},
	{ city: "Flint", state: "Michigan", metroAreaName: "Flint, Michigan"},
	{ city: "Florence", state: "South Carolina", metroAreaName: "Florence, South Carolina"},
	{ city: "Fort Collins-Loveland", state: "Colorado", metroAreaName: "Fort Collins-Loveland, Colorado"},
	{ city: "Fort Smith", state: "Arkansas-Oklahoma", metroAreaName: "Fort Smith, Arkansas-Oklahoma"},
	{ city: "Fort Wayne", state: "Indiana", metroAreaName: "Fort Wayne, Indiana"},
	{ city: "Fresno", state: "California", metroAreaName: "Fresno, California"},
	{ city: "Gainesville", state: "Florida", metroAreaName: "Gainesville, Florida"},
	{ city: "Grand Rapids-Wyoming", state: "Michigan", metroAreaName: "Grand Rapids-Wyoming, Michigan"},
	{ city: "Greeley", state: "Colorado", metroAreaName: "Greeley, Colorado"},
	{ city: "Green Bay", state: "Wisconsin", metroAreaName: "Green Bay, Wisconsin"},
	{ city: "Greensboro-High Point", state: "North Carolina", metroAreaName: "Greensboro-High Point, North Carolina"},
	{ city: "Greenville-Mauldin-Easley", state: "South Carolina", metroAreaName: "Greenville-Mauldin-Easley, South Carolina"},
	{ city: "Gulfport-Biloxi", state: "Mississippi", metroAreaName: "Gulfport-Biloxi, Mississippi"},
	{ city: "Hagerstown-Martinsburg", state: "Maryland-West Virginia", metroAreaName: "Hagerstown-Martinsburg, Maryland-West Virginia"},
	{ city: "Harrisburg-Carlisle", state: "Pennsylvania", metroAreaName: "Harrisburg-Carlisle, Pennsylvania"},
	{ city: "Hartford-West Hartford-East Hartford", state: "Connecticut", metroAreaName: "Hartford-West Hartford-East Hartford, Connecticut"},
	{ city: "Hickory-Lenoir-Morganton", state: "North Carolina", metroAreaName: "Hickory-Lenoir-Morganton, North Carolina"},
	{ city: "Hilton Head Island-Beaufort", state: "South Carolina", metroAreaName: "Hilton Head Island-Beaufort, South Carolina"},
	{ city: "Holland-Grand Haven", state: "Michigan", metroAreaName: "Holland-Grand Haven, Michigan"},
	{ city: "Honolulu", state: "Hawaii", metroAreaName: "Honolulu, Hawaii"},
	{ city: "Houma-Bayou Cane-Thibodaux", state: "Louisiana", metroAreaName: "Houma-Bayou Cane-Thibodaux, Louisiana"},
	{ city: "Houston-Sugar Land-Baytown", state: "Texas", metroAreaName: "Houston-Sugar Land-Baytown, Texas"},
	{ city: "Huntington-Ashland", state: "West Virginia-Kentucky-Ohio", metroAreaName: "Huntington-Ashland, West Virginia-Kentucky-Ohio"},
	{ city: "Huntsville", state: "Alabama", metroAreaName: "Huntsville, Alabama"},
	{ city: "Indianapolis-Carmel", state: "Indiana", metroAreaName: "Indianapolis-Carmel, Indiana"},
	{ city: "Jackson", state: "Mississippi", metroAreaName: "Jackson, Mississippi"},
	{ city: "Jacksonville", state: "Florida", metroAreaName: "Jacksonville, Florida"},
	{ city: "Johnson City", state: "Tennessee", metroAreaName: "Johnson City, Tennessee"},
	{ city: "Kalamazoo-Portage", state: "Michigan", metroAreaName: "Kalamazoo-Portage, Michigan"},
	{ city: "Kansas City", state: "Missouri-Kansas", metroAreaName: "Kansas City, Missouri-Kansas"},
	{ city: "Kennewick-Pasco-Richland", state: "Washington", metroAreaName: "Kennewick-Pasco-Richland, Washington"},
	{ city: "Killeen-Temple-Fort Hood", state: "Texas", metroAreaName: "Killeen-Temple-Fort Hood, Texas"},
	{ city: "Kingsport-Bristol-Bristol", state: "Tennessee-Virginia", metroAreaName: "Kingsport-Bristol-Bristol, Tennessee-Virginia"},
	{ city: "Knoxville", state: "Tennessee", metroAreaName: "Knoxville, Tennessee"},
	{ city: "Lafayette", state: "Indiana", metroAreaName: "Lafayette, Indiana"},
	{ city: "Lafayette", state: "Louisiana", metroAreaName: "Lafayette, Louisiana"},
	{ city: "Lake Charles", state: "Louisiana", metroAreaName: "Lake Charles, Louisiana"},
	{ city: "Lake Havasu City-Kingman", state: "Arizona", metroAreaName: "Lake Havasu City-Kingman, Arizona"},
	{ city: "Lakeland-Winter Haven", state: "Florida", metroAreaName: "Lakeland-Winter Haven, Florida"},
	{ city: "Lancaster", state: "Pennsylvania", metroAreaName: "Lancaster, Pennsylvania"},
	{ city: "Lansing-East Lansing", state: "Michigan", metroAreaName: "Lansing-East Lansing, Michigan"},
	{ city: "Laredo", state: "Texas", metroAreaName: "Laredo, Texas"},
	{ city: "Las Cruces", state: "New Mexico", metroAreaName: "Las Cruces, New Mexico"},
	{ city: "Las Vegas-Paradise", state: "Nevada", metroAreaName: "Las Vegas-Paradise, Nevada"},
	{ city: "Lexington-Fayette", state: "Kentucky", metroAreaName: "Lexington-Fayette, Kentucky"},
	{ city: "Lincoln", state: "Nebraska", metroAreaName: "Lincoln, Nebraska"},
	{ city: "Little Rock-North Little Rock-Conway", state: "Arkansas", metroAreaName: "Little Rock-North Little Rock-Conway, Arkansas"},
	{ city: "Longview", state: "Texas", metroAreaName: "Longview, Texas"},
	{ city: "Los Angeles-Long Beach-Santa Ana", state: "California", metroAreaName: "Los Angeles-Long Beach-Santa Ana, California"},
	{ city: "Louisville-Jefferson County", state: "Kentucky-Indiana", metroAreaName: "Louisville-Jefferson County, Kentucky-Indiana"},
	{ city: "Lubbock", state: "Texas", metroAreaName: "Lubbock, Texas"},
	{ city: "Lynchburg", state: "Virginia", metroAreaName: "Lynchburg, Virginia"},
	{ city: "Macon", state: "Georgia", metroAreaName: "Macon, Georgia"},
	{ city: "Madison", state: "Wisconsin", metroAreaName: "Madison, Wisconsin"},
	{ city: "Manchester-Nashua", state: "New Hampshire", metroAreaName: "Manchester-Nashua, New Hampshire"},
	{ city: "McAllen-Edinburg-Mission", state: "Texas", metroAreaName: "McAllen-Edinburg-Mission, Texas"},
	{ city: "Medford", state: "Oregon", metroAreaName: "Medford, Oregon"},
	{ city: "Memphis", state: "Tennessee-Mississippi-Arkansas", metroAreaName: "Memphis, Tennessee-Mississippi-Arkansas"},
	{ city: "Merced", state: "California", metroAreaName: "Merced, California"},
	{ city: "Miami-Fort Lauderdale-Pompano Beach", state: "Florida", metroAreaName: "Miami-Fort Lauderdale-Pompano Beach, Florida"},
	{ city: "Milwaukee-Waukesha-West Allis", state: "Wisconsin", metroAreaName: "Milwaukee-Waukesha-West Allis, Wisconsin"},
	{ city: "Minneapolis-St. Paul-Bloomington", state: "Minnesota-Wisconsin", metroAreaName: "Minneapolis-St. Paul-Bloomington, Minnesota-Wisconsin"},
	{ city: "Mobile", state: "Alabama", metroAreaName: "Mobile, Alabama"},
	{ city: "Modesto", state: "California", metroAreaName: "Modesto, California"},
	{ city: "Montgomery", state: "Alabama", metroAreaName: "Montgomery, Alabama"},
	{ city: "Myrtle Beach-North Myrtle Beach-Conway", state: "South Carolina", metroAreaName: "Myrtle Beach-North Myrtle Beach-Conway, South Carolina"},
	{ city: "Naples-Marco Island", state: "Florida", metroAreaName: "Naples-Marco Island, Florida"},
	{ city: "Nashville-Davidson-Murfreesboro-Franklin", state: "Tennessee", metroAreaName: "Nashville-Davidson-Murfreesboro-Franklin, Tennessee"},
	{ city: "New Haven-Milford", state: "Connecticut", metroAreaName: "New Haven-Milford, Connecticut"},
	{ city: "New Orleans-Metairie-Kenner", state: "Louisiana", metroAreaName: "New Orleans-Metairie-Kenner, Louisiana"},
	{ city: "New York-Northern New Jersey-Long Island", state: "New York-New Jersey-Pennsylvania", metroAreaName: "New York-Northern New Jersey-Long Island, New York-New Jersey-Pennsylvania"},
	{ city: "North Port-Bradenton-Sarasota", state: "Florida", metroAreaName: "North Port-Bradenton-Sarasota, Florida"},
	{ city: "Norwich-New London", state: "Connecticut", metroAreaName: "Norwich-New London, Connecticut"},
	{ city: "Ocala", state: "Florida", metroAreaName: "Ocala, Florida"},
	{ city: "Ogden-Clearfield", state: "Utah", metroAreaName: "Ogden-Clearfield, Utah"},
	{ city: "Oklahoma City", state: "Oklahoma", metroAreaName: "Oklahoma City, Oklahoma"},
	{ city: "Olympia", state: "Washington", metroAreaName: "Olympia, Washington"},
	{ city: "Omaha-Council Bluffs", state: "Nebraska-Iowa", metroAreaName: "Omaha-Council Bluffs, Nebraska-Iowa"},
	{ city: "Orlando-Kissimmee-Sanford", state: "Florida", metroAreaName: "Orlando-Kissimmee-Sanford, Florida"},
	{ city: "Oxnard-Thousand Oaks-Ventura", state: "California", metroAreaName: "Oxnard-Thousand Oaks-Ventura, California"},
	{ city: "Palm Bay-Melbourne-Titusville", state: "Florida", metroAreaName: "Palm Bay-Melbourne-Titusville, Florida"},
	{ city: "Pensacola-Ferry Pass-Brent", state: "Florida", metroAreaName: "Pensacola-Ferry Pass-Brent, Florida"},
	{ city: "Peoria", state: "Illinois", metroAreaName: "Peoria, Illinois"},
	{ city: "Philadelphia-Camden-Wilmington", state: "Pennsylvania-New Jersey-Delaware-Maryland", metroAreaName: "Philadelphia-Camden-Wilmington, Pennsylvania-New Jersey-Delaware-Maryland"},
	{ city: "Phoenix-Mesa-Glendale", state: "Arizona", metroAreaName: "Phoenix-Mesa-Glendale, Arizona"},
	{ city: "Pittsburgh", state: "Pennsylvania", metroAreaName: "Pittsburgh, Pennsylvania"},
	{ city: "Port St. Lucie", state: "Florida", metroAreaName: "Port St. Lucie, Florida"},
	{ city: "Portland-South Portland-Biddeford", state: "Maine", metroAreaName: "Portland-South Portland-Biddeford, Maine"},
	{ city: "Portland-Vancouver-Hillsboro", state: "Oregon-Washington", metroAreaName: "Portland-Vancouver-Hillsboro, Oregon-Washington"},
	{ city: "Poughkeepsie-Newburgh-Middletown", state: "New York", metroAreaName: "Poughkeepsie-Newburgh-Middletown, New York"},
	{ city: "Prescott", state: "Arizona", metroAreaName: "Prescott, Arizona"},
	{ city: "Providence-New Bedford-Fall River", state: "Rhode Island-Massachusetts", metroAreaName: "Providence-New Bedford-Fall River, Rhode Island-Massachusetts"},
	{ city: "Provo-Orem", state: "Utah", metroAreaName: "Provo-Orem, Utah"},
	{ city: "Raleigh-Cary", state: "North Carolina", metroAreaName: "Raleigh-Cary, North Carolina"},
	{ city: "Reading", state: "Pennsylvania", metroAreaName: "Reading, Pennsylvania"},
	{ city: "Reno-Sparks", state: "Nevada", metroAreaName: "Reno-Sparks, Nevada"},
	{ city: "Richmond", state: "Virginia", metroAreaName: "Richmond, Virginia"},
	{ city: "Riverside-San Bernardino-Ontario", state: "California", metroAreaName: "Riverside-San Bernardino-Ontario, California"},
	{ city: "Roanoke", state: "Virginia", metroAreaName: "Roanoke, Virginia"},
	{ city: "Rochester", state: "New York", metroAreaName: "Rochester, New York"},
	{ city: "Rockford", state: "Illinois", metroAreaName: "Rockford, Illinois"},
	{ city: "Sacramento-Arden-Arcade-Roseville", state: "California", metroAreaName: "Sacramento-Arden-Arcade-Roseville, California"},
	{ city: "Salem", state: "Oregon", metroAreaName: "Salem, Oregon"},
	{ city: "Salinas", state: "California", metroAreaName: "Salinas, California"},
	{ city: "Salt Lake City", state: "Utah", metroAreaName: "Salt Lake City, Utah"},
	{ city: "San Antonio-New Braunfels", state: "Texas", metroAreaName: "San Antonio-New Braunfels, Texas"},
	{ city: "San Diego-Carlsbad-San Marcos", state: "California", metroAreaName: "San Diego-Carlsbad-San Marcos, California"},
	{ city: "San Francisco-Oakland-Fremont", state: "California", metroAreaName: "San Francisco-Oakland-Fremont, California"},
	{ city: "San Jose-Sunnyvale-Santa Clara", state: "California", metroAreaName: "San Jose-Sunnyvale-Santa Clara, California"},
	{ city: "San Luis Obispo-Paso Robles", state: "California", metroAreaName: "San Luis Obispo-Paso Robles, California"},
	{ city: "Santa Barbara-Santa Maria-Goleta", state: "California", metroAreaName: "Santa Barbara-Santa Maria-Goleta, California"},
	{ city: "Santa Cruz-Watsonville", state: "California", metroAreaName: "Santa Cruz-Watsonville, California"},
	{ city: "Santa Rosa-Petaluma", state: "California", metroAreaName: "Santa Rosa-Petaluma, California"},
	{ city: "Savannah", state: "Georgia", metroAreaName: "Savannah, Georgia"},
	{ city: "Scranton-Wilkes-Barre", state: "Pennsylvania", metroAreaName: "Scranton-Wilkes-Barre, Pennsylvania"},
	{ city: "Seaford", state: "Delaware", metroAreaName: "Seaford, Delaware"},
	{ city: "Seattle-Tacoma-Bellevue", state: "Washington", metroAreaName: "Seattle-Tacoma-Bellevue, Washington"},
	{ city: "Shreveport-Bossier City", state: "Louisiana", metroAreaName: "Shreveport-Bossier City, Louisiana"},
	{ city: "Sioux Falls", state: "South Dakota", metroAreaName: "Sioux Falls, South Dakota"},
	{ city: "South Bend-Mishawaka", state: "Indiana-Michigan", metroAreaName: "South Bend-Mishawaka, Indiana-Michigan"},
	{ city: "Spartanburg", state: "South Carolina", metroAreaName: "Spartanburg, South Carolina"},
	{ city: "Spokane", state: "Washington", metroAreaName: "Spokane, Washington"},
	{ city: "Springfield", state: "Illinois", metroAreaName: "Springfield, Illinois"},
	{ city: "Springfield", state: "Massachusetts", metroAreaName: "Springfield, Massachusetts"},
	{ city: "Springfield", state: "Missouri", metroAreaName: "Springfield, Missouri"},
	{ city: "St. Cloud", state: "Minnesota", metroAreaName: "St. Cloud, Minnesota"},
	{ city: "St. Louis", state: "Missouri-Illinois", metroAreaName: "St. Louis, Missouri-Illinois"},
	{ city: "Stockton", state: "California", metroAreaName: "Stockton, California"},
	{ city: "Syracuse", state: "New York", metroAreaName: "Syracuse, New York"},
	{ city: "Tallahassee", state: "Florida", metroAreaName: "Tallahassee, Florida"},
	{ city: "Tampa-St. Petersburg-Clearwater", state: "Florida", metroAreaName: "Tampa-St. Petersburg-Clearwater, Florida"},
	{ city: "Toledo", state: "Ohio", metroAreaName: "Toledo, Ohio"},
	{ city: "Topeka", state: "Kansas", metroAreaName: "Topeka, Kansas"},
	{ city: "Trenton-Ewing", state: "New Jersey", metroAreaName: "Trenton-Ewing, New Jersey"},
	{ city: "Tucson", state: "Arizona", metroAreaName: "Tucson, Arizona"},
	{ city: "Tulsa", state: "Oklahoma", metroAreaName: "Tulsa, Oklahoma"},
	{ city: "Tuscaloosa", state: "Alabama", metroAreaName: "Tuscaloosa, Alabama"},
	{ city: "Tyler", state: "Texas", metroAreaName: "Tyler, Texas"},
	{ city: "Utica-Rome", state: "New York", metroAreaName: "Utica-Rome, New York"},
	{ city: "Vallejo-Fairfield", state: "California", metroAreaName: "Vallejo-Fairfield, California"},
	{ city: "Virginia Beach-Norfolk-Newport News", state: "Virginia-North Carolina", metroAreaName: "Virginia Beach-Norfolk-Newport News, Virginia-North Carolina"},
	{ city: "Visalia-Porterville", state: "California", metroAreaName: "Visalia-Porterville, California"},
	{ city: "Waco", state: "Texas", metroAreaName: "Waco, Texas"},
	{ city: "Washington-Arlington-Alexandria", state: "Washington DC-Virginia-Maryland-West Virginia", metroAreaName: "Washington-Arlington-Alexandria, Washington DC-Virginia-Maryland-West Virginia"},
	{ city: "Wichita", state: "Kansas", metroAreaName: "Wichita, Kansas"},
	{ city: "Wilmington", state: "North Carolina", metroAreaName: "Wilmington, North Carolina"},
	{ city: "Winston-Salem", state: "North Carolina", metroAreaName: "Winston-Salem, North Carolina"},
	{ city: "Worcester", state: "Massachusetts", metroAreaName: "Worcester, Massachusetts"},
	{ city: "Yakima", state: "Washington", metroAreaName: "Yakima, Washington"},
	{ city: "York-Hanover", state: "Pennsylvania", metroAreaName: "York-Hanover, Pennsylvania"},
	{ city: "Youngstown-Warren-Boardman", state: "Ohio-Pennsylvania", metroAreaName: "Youngstown-Warren-Boardman, Ohio-Pennsylvania"},
	{ city: "Yuma", state: "Arizona", metroAreaName: "Yuma, Arizona"}
]

const STATE_NAMES = {
	AL: "Alabama",
	AK: "Alaska",
	AZ: "Arizona",
	AR: "Arkansas",
	CA: "California",
	CO: "Colorado",
	CT: "Connecticut",
	DC: "Washington DC",
	DE: "Delaware",
	FL: "Florida",
	GA: "Georgia",
	HI: "Hawaii",
	ID: "Idaho",
	IL: "Illinois",
	IN: "Indiana",
	IA: "Iowa",
	KS: "Kansas",
	KY: "Kentucky",
	LA: "Louisiana",
	ME: "Maine",
	MD: "Maryland",
	MA: "Massachusetts",
	MI: "Michigan",
	MN: "Minnesota",
	MS: "Mississippi",
	MO: "Missouri",
	MT: "Montana",
	NE: "Nebraska",
	NV: "Nevada",
	NH: "New Hampshire",
	NJ: "New Jersey",
	NM: "New Mexico",
	NY: "New York",
	NC: "North Carolina",
	ND: "North Dakota",
	OH: "Ohio",
	OK: "Oklahoma",
	OR: "Oregon",
	PA: "Pennsylvania",
	RI: "Rhode Island",
	SC: "South Carolina",
	SD: "South Dakota",
	TN: "Tennessee",
	TX: "Texas",
	UT: "Utah",
	VT: "Vermont",
	VA: "Virginia",
	WA: "Washington",
	WV: "West Virginia",
	WI: "Wisconsin",
	WY: "Wyoming",

	// edge case
	"SC Micropolitan Statistical Area": "South Carolina",
	"DE Micropolitan Statistical Area": "Delaware",
	"AL Micropolitan Statistical Area": "Alabama"
}

module.exports = {
	METRO_AREAS,
	STATE_NAMES,
}
