const fs = require("fs");
const { STATE_NAMES, METRO_AREAS } = require("../sharedValues")
// data from: https://belonging.berkeley.edu/most-least-segregated-metro-regions
const dataArray = [
	{ metroArea: "New York-Northern New Jersey-Long Island, NY-NJ-PA", divergence: 0.4302},
	{ metroArea: "Chicago-Joliet-Naperville, IL-IN-WI", divergence: 0.428},
	{ metroArea: "Milwaukee-Waukesha-West Allis, WI", divergence: 0.3811},
	{ metroArea: "Detroit-Warren-Livonia, MI", divergence: 0.3789},
	{ metroArea: "Miami-Fort Lauderdale-Pompano Beach, FL", divergence: 0.3702},
	{ metroArea: "Los Angeles-Long Beach-Santa Ana, CA", divergence: 0.3534},
	{ metroArea: "Trenton-Ewing, NJ", divergence: 0.3455},
	{ metroArea: "Cleveland-Elyria-Mentor, OH", divergence: 0.3324},
	{ metroArea: "Philadelphia-Camden-Wilmington, PA-NJ-DE-MD", divergence: 0.3294},
	{ metroArea: "Beaumont-Port Arthur, TX", divergence: 0.3233},
	{ metroArea: "New Orleans-Metairie-Kenner, LA", divergence: 0.323},
	{ metroArea: "Atlanta-Sandy Springs-Marietta, GA", divergence: 0.3203},
	{ metroArea: "Memphis, TN-MS-AR", divergence: 0.3155},
	{ metroArea: "Baltimore-Towson, MD", divergence: 0.312},
	{ metroArea: "Washington-Arlington-Alexandria, DC-VA-MD-WV", divergence: 0.3118},
	{ metroArea: "Houston-Sugar Land-Baytown, TX", divergence: 0.2995},
	{ metroArea: "Birmingham-Hoover, AL", divergence: 0.2954},
	{ metroArea: "Dallas-Fort Worth-Arlington, TX", divergence: 0.2864},
	{ metroArea: "St. Louis, MO-IL", divergence: 0.2822},
	{ metroArea: "Salinas, CA", divergence: 0.2755},
	{ metroArea: "Buffalo-Niagara Falls, NY", divergence: 0.27},
	{ metroArea: "Baton Rouge, LA", divergence: 0.2689},
	{ metroArea: "Hartford-West Hartford-East Hartford, CT", divergence: 0.268},
	{ metroArea: "Mobile, AL", divergence: 0.2671},
	{ metroArea: "San Francisco-Oakland-Fremont, CA", divergence: 0.2648},
	{ metroArea: "Flint, MI", divergence: 0.2642},
	{ metroArea: "Atlantic City-Hammonton, NJ", divergence: 0.2635},
	{ metroArea: "Boston-Cambridge-Quincy, MA-NH", divergence: 0.2556},
	{ metroArea: "Jackson, MS", divergence: 0.2532},
	{ metroArea: "Tuscaloosa, AL", divergence: 0.2531},
	{ metroArea: "Montgomery, AL", divergence: 0.2494},
	{ metroArea: "Springfield, MA", divergence: 0.2461},
	{ metroArea: "Lake Charles, LA", divergence: 0.2451},
	{ metroArea: "Bridgeport-Stamford-Norwalk, CT", divergence: 0.2424},
	{ metroArea: "Reading, PA", divergence: 0.2385},
	{ metroArea: "Shreveport-Bossier City, LA", divergence: 0.2375},
	{ metroArea: "Bakersfield-Delano, CA", divergence: 0.2368},
	{ metroArea: "San Diego-Carlsbad-San Marcos, CA", divergence: 0.2364},
	{ metroArea: "Richmond, VA", divergence: 0.2335},
	{ metroArea: "New Haven-Milford, CT", divergence: 0.2333},
	{ metroArea: "Yakima, WA", divergence: 0.2324},
	{ metroArea: "Indianapolis-Carmel, IN", divergence: 0.2322},
	{ metroArea: "Columbus, GA-AL", divergence: 0.229},
	{ metroArea: "Greensboro-High Point, NC", divergence: 0.2287},
	{ metroArea: "San Jose-Sunnyvale-Santa Clara, CA", divergence: 0.2258},
	{ metroArea: "Winston-Salem, NC", divergence: 0.2257},
	{ metroArea: "Little Rock-North Little Rock-Conway, AR", divergence: 0.2243},
	{ metroArea: "Charlotte-Gastonia-Rock Hill, NC-SC", divergence: 0.2236},
	{ metroArea: "Phoenix-Mesa-Glendale, AZ", divergence: 0.2199},
	{ metroArea: "Santa Cruz-Watsonville, CA", divergence: 0.2183},
	{ metroArea: "Dayton, OH", divergence: 0.2178},
	{ metroArea: "Oxnard-Thousand Oaks-Ventura, CA", divergence: 0.2166},
	{ metroArea: "Tucson, AZ", divergence: 0.2158},
	{ metroArea: "Columbus, OH", divergence: 0.2145},
	{ metroArea: "Amarillo, TX", divergence: 0.2144},
	{ metroArea: "Yuma, AZ", divergence: 0.2143},
	{ metroArea: "Rochester, NY", divergence: 0.2131},
	{ metroArea: "Naples-Marco Island, FL", divergence: 0.2127},
	{ metroArea: "Orlando-Kissimmee-Sanford, FL", divergence: 0.2111},
	{ metroArea: "Macon, GA", divergence: 0.2105},
	{ metroArea: "Honolulu, HI", divergence: 0.209},
	{ metroArea: "Kansas City, MO-KS", divergence: 0.2085},
	{ metroArea: "Columbia, SC", divergence: 0.2071},
	{ metroArea: "Hilton Head Island-Beaufort, SC Micropolitan Statistical Area", divergence: 0.2056},
	{ metroArea: "Savannah, GA", divergence: 0.2054},
	{ metroArea: "Cincinnati-Middletown, OH-KY-IN", divergence: 0.2051},
	{ metroArea: "Durham-Chapel Hill, NC", divergence: 0.2039},
	{ metroArea: "Jacksonville, FL", divergence: 0.2035},
	{ metroArea: "Providence-New Bedford-Fall River, RI-MA", divergence: 0.2007},
	{ metroArea: "Oklahoma City, OK", divergence: 0.1969},
	{ metroArea: "Chattanooga, TN-GA", divergence: 0.1959},
	{ metroArea: "Fresno, CA", divergence: 0.195},
	{ metroArea: "Omaha-Council Bluffs, NE-IA", divergence: 0.193},
	{ metroArea: "Tampa-St. Petersburg-Clearwater, FL", divergence: 0.1926},
	{ metroArea: "Virginia Beach-Norfolk-Newport News, VA-NC", divergence: 0.1925},
	{ metroArea: "Tyler, TX", divergence: 0.1905},
	{ metroArea: "Santa Barbara-Santa Maria-Goleta, CA", divergence: 0.1896},
	{ metroArea: "San Antonio-New Braunfels, TX", divergence: 0.1881},
	{ metroArea: "Denver-Aurora-Broomfield, CO", divergence: 0.1879},
	{ metroArea: "Louisville-Jefferson County, KY-IN", divergence: 0.1877},
	{ metroArea: "Fort Wayne, IN", divergence: 0.1871},
	{ metroArea: "Sacramento--Arden-Arcade--Roseville, CA", divergence: 0.1869},
	{ metroArea: "Harrisburg-Carlisle, PA", divergence: 0.1857},
	{ metroArea: "Peoria, IL", divergence: 0.1853},
	{ metroArea: "Nashville-Davidson--Murfreesboro--Franklin, TN", divergence: 0.185},
	{ metroArea: "Augusta-Richmond County, GA-SC", divergence: 0.184},
	{ metroArea: "Toledo, OH", divergence: 0.1818},
	{ metroArea: "Riverside-San Bernardino-Ontario, CA", divergence: 0.1813},
	{ metroArea: "Champaign-Urbana, IL", divergence: 0.181},
	{ metroArea: "Cape Coral-Fort Myers, FL", divergence: 0.1806},
	{ metroArea: "South Bend-Mishawaka, IN-MI", divergence: 0.1788},
	{ metroArea: "Ann Arbor, MI", divergence: 0.1781},
	{ metroArea: "Raleigh-Cary, NC", divergence: 0.1775},
	{ metroArea: "Grand Rapids-Wyoming, MI", divergence: 0.1774},
	{ metroArea: "Wichita, KS", divergence: 0.1771},
	{ metroArea: "Waco, TX", divergence: 0.1759},
	{ metroArea: "Las Vegas-Paradise, NV", divergence: 0.1754},
	{ metroArea: "Rockford, IL", divergence: 0.1751},
	{ metroArea: "Albuquerque, NM", divergence: 0.1744},
	{ metroArea: "Syracuse, NY", divergence: 0.1731},
	{ metroArea: "Allentown-Bethlehem-Easton, PA-NJ", divergence: 0.1723},
	{ metroArea: "Tulsa, OK", divergence: 0.1709},
	{ metroArea: "Austin-Round Rock-San Marcos, TX", divergence: 0.1695},
	{ metroArea: "Fort Smith, AR-OK", divergence: 0.1691},
	{ metroArea: "Huntsville, AL", divergence: 0.1685},
	{ metroArea: "Youngstown-Warren-Boardman, OH-PA", divergence: 0.1682},
	{ metroArea: "College Station-Bryan, TX", divergence: 0.1677},
	{ metroArea: "Stockton, CA", divergence: 0.1671},
	{ metroArea: "Tallahassee, FL", divergence: 0.1659},
	{ metroArea: "Port St. Lucie, FL", divergence: 0.1651},
	{ metroArea: "Akron, OH", divergence: 0.165},
	{ metroArea: "Roanoke, VA", divergence: 0.1648},
	{ metroArea: "Athens-Clarke County, GA", divergence: 0.1628},
	{ metroArea: "Deltona-Daytona Beach-Ormond Beach, FL", divergence: 0.161},
	{ metroArea: "Corpus Christi, TX", divergence: 0.1594},
	{ metroArea: "Minneapolis-St. Paul-Bloomington, MN-WI", divergence: 0.1594},
	{ metroArea: "Lakeland-Winter Haven, FL", divergence: 0.1592},
	{ metroArea: "Kennewick-Pasco-Richland, WA", divergence: 0.1589},
	{ metroArea: "Fayetteville-Springdale-Rogers, AR-MO", divergence: 0.157},
	{ metroArea: "Vallejo-Fairfield, CA", divergence: 0.1553},
	{ metroArea: "Utica-Rome, NY", divergence: 0.1548},
	{ metroArea: "Lafayette, LA", divergence: 0.1538},
	{ metroArea: "Pittsburgh, PA", divergence: 0.1529},
	{ metroArea: "Albany-Schenectady-Troy, NY", divergence: 0.1507},
	{ metroArea: "Lubbock, TX", divergence: 0.1495},
	{ metroArea: "Worcester, MA", divergence: 0.149},
	{ metroArea: "Charleston-North Charleston-Summerville, SC", divergence: 0.1468},
	{ metroArea: "Seattle-Tacoma-Bellevue, WA", divergence: 0.1468},
	{ metroArea: "Scranton--Wilkes-Barre, PA", divergence: 0.1451},
	{ metroArea: "Florence, SC", divergence: 0.1437},
	{ metroArea: "North Port-Bradenton-Sarasota, FL", divergence: 0.1437},
	{ metroArea: "Lansing-East Lansing, MI", divergence: 0.1432},
	{ metroArea: "Poughkeepsie-Newburgh-Middletown, NY", divergence: 0.1421},
	{ metroArea: "Springfield, IL", divergence: 0.1411},
	{ metroArea: "Greenville-Mauldin-Easley, SC", divergence: 0.1396},
	{ metroArea: "Gainesville, FL", divergence: 0.1392},
	{ metroArea: "Gulfport-Biloxi, MS", divergence: 0.1369},
	{ metroArea: "Houma-Bayou Cane-Thibodaux, LA", divergence: 0.136},
	{ metroArea: "Topeka, KS", divergence: 0.1351},
	{ metroArea: "Killeen-Temple-Fort Hood, TX", divergence: 0.1331},
	{ metroArea: "Reno-Sparks, NV", divergence: 0.1322},
	{ metroArea: "Lexington-Fayette, KY", divergence: 0.1306},
	{ metroArea: "Spartanburg, SC", divergence: 0.1298},
	{ metroArea: "Pensacola-Ferry Pass-Brent, FL", divergence: 0.1294},
	{ metroArea: "Lancaster, PA", divergence: 0.1288},
	{ metroArea: "Erie, PA", divergence: 0.1284},
	{ metroArea: "Visalia-Porterville, CA", divergence: 0.1264},
	{ metroArea: "Ocala, FL", divergence: 0.1257},
	{ metroArea: "Lafayette, IN", divergence: 0.1255},
	{ metroArea: "Salt Lake City, UT", divergence: 0.1253},
	{ metroArea: "Norwich-New London, CT", divergence: 0.1242},
	{ metroArea: "Salem, OR", divergence: 0.1235},
	{ metroArea: "Anchorage, AK", divergence: 0.1229},
	{ metroArea: "Green Bay, WI", divergence: 0.1225},
	{ metroArea: "Clarksville, TN-KY", divergence: 0.1218},
	{ metroArea: "Kalamazoo-Portage, MI", divergence: 0.121},
	{ metroArea: "Modesto, CA", divergence: 0.1209},
	{ metroArea: "York-Hanover, PA", divergence: 0.12},
	{ metroArea: "Wilmington, NC", divergence: 0.1192},
	{ metroArea: "Seaford, DE Micropolitan Statistical Area", divergence: 0.1176},
	{ metroArea: "Des Moines-West Des Moines, IA", divergence: 0.1158},
	{ metroArea: "Longview, TX", divergence: 0.1147},
	{ metroArea: "Davenport-Moline-Rock Island, IA-IL", divergence: 0.114},
	{ metroArea: "Las Cruces, NM", divergence: 0.114},
	{ metroArea: "Myrtle Beach-North Myrtle Beach-Conway, SC", divergence: 0.1132},
	{ metroArea: "Greeley, CO", divergence: 0.1108},
	{ metroArea: "Merced, CA", divergence: 0.1108},
	{ metroArea: "Knoxville, TN", divergence: 0.1088},
	{ metroArea: "Elkhart-Goshen, IN", divergence: 0.107},
	{ metroArea: "Fayetteville, NC", divergence: 0.1068},
	{ metroArea: "Hickory-Lenoir-Morganton, NC", divergence: 0.106},
	{ metroArea: "Portland-Vancouver-Hillsboro, OR-WA", divergence: 0.1051},
	{ metroArea: "Canton-Massillon, OH", divergence: 0.1028},
	{ metroArea: "Santa Rosa-Petaluma, CA", divergence: 0.1024},
	{ metroArea: "Lynchburg, VA", divergence: 0.1009},
	{ metroArea: "Palm Bay-Melbourne-Titusville, FL", divergence: 0.1007},
	{ metroArea: "Sioux Falls, SD", divergence: 0.0995},
	{ metroArea: "El Paso, TX", divergence: 0.0986},
	{ metroArea: "Madison, WI", divergence: 0.0944},
	{ metroArea: "Binghamton, NY", divergence: 0.0928},
	{ metroArea: "Charlottesville, VA", divergence: 0.0924},
	{ metroArea: "Holland-Grand Haven, MI", divergence: 0.0917},
	{ metroArea: "Manchester-Nashua, NH", divergence: 0.09},
	{ metroArea: "Daphne-Fairhope-Foley, AL Micropolitan Statistical Area", divergence: 0.0897},
	{ metroArea: "Evansville, IN-KY", divergence: 0.0894},
	{ metroArea: "St. Cloud, MN", divergence: 0.0877},
	{ metroArea: "Lincoln, NE", divergence: 0.0873},
	{ metroArea: "San Luis Obispo-Paso Robles, CA", divergence: 0.0873},
	{ metroArea: "Charleston, WV", divergence: 0.084},
	{ metroArea: "Lake Havasu City-Kingman, AZ", divergence: 0.084},
	{ metroArea: "Asheville, NC", divergence: 0.0835},
	{ metroArea: "Boulder, CO", divergence: 0.0808},
	{ metroArea: "Colorado Springs, CO", divergence: 0.0791},
	{ metroArea: "Chico, CA", divergence: 0.0789},
	{ metroArea: "Hagerstown-Martinsburg, MD-WV", divergence: 0.0789},
	{ metroArea: "Ogden-Clearfield, UT", divergence: 0.0789},
	{ metroArea: "Appleton, WI", divergence: 0.078},
	{ metroArea: "Cedar Rapids, IA", divergence: 0.0717},
	{ metroArea: "Boise City-Nampa, ID", divergence: 0.0709},
	{ metroArea: "Bellingham, WA", divergence: 0.0696},
	{ metroArea: "Barnstable Town, MA", divergence: 0.0692},
	{ metroArea: "Fargo, ND-MN", divergence: 0.0685},
	{ metroArea: "Olympia, WA", divergence: 0.0671},
	{ metroArea: "Bremerton-Silverdale, WA", divergence: 0.0648},
	{ metroArea: "Medford, OR", divergence: 0.0615},
	{ metroArea: "Johnson City, TN", divergence: 0.0604},
	{ metroArea: "Provo-Orem, UT", divergence: 0.0586},
	{ metroArea: "McAllen-Edinburg-Mission, TX", divergence: 0.0582},
	{ metroArea: "Brownsville-Harlingen, TX", divergence: 0.0575},
	{ metroArea: "Huntington-Ashland, WV-KY-OH", divergence: 0.0559},
	{ metroArea: "Duluth, MN-WI", divergence: 0.0558},
	{ metroArea: "Crestview-Fort Walton Beach-Destin, FL", divergence: 0.0537},
	{ metroArea: "Prescott, AZ", divergence: 0.0531},
	{ metroArea: "Eugene-Springfield, OR", divergence: 0.053},
	{ metroArea: "Portland-South Portland-Biddeford, ME", divergence: 0.0527},
	{ metroArea: "Burlington-South Burlington, VT", divergence: 0.0526},
	{ metroArea: "Spokane, WA", divergence: 0.0507},
	{ metroArea: "Springfield, MO", divergence: 0.0487},
	{ metroArea: "Fort Collins-Loveland, CO", divergence: 0.0457},
	{ metroArea: "Kingsport-Bristol-Bristol, TN-VA", divergence: 0.0377},
	{ metroArea: "Laredo, TX", divergence: 0.0258}
]

const results = []
dataArray.forEach(data => {
	let [cityInfo, stateInfo] = data.metroArea.split(", ")
	const citiesFromData = cityInfo.split("-")
	const statesFromData = stateInfo.split("-")

	const matchesForCity = METRO_AREAS.find(metroAreaInfo => {
		const citiesFromMetroArea = metroAreaInfo.city.split("-")
		for (const city of citiesFromData) {
			if (citiesFromMetroArea.includes(city)) {
				// if we have a matching city name verify we have a matching state as well
				const stateFromMetroArea = metroAreaInfo.state.split("-")
				for (const state of statesFromData) {
					if (stateFromMetroArea.includes(STATE_NAMES[state])) {
						return true
					}
				}
			}
		}
		return false
	})

	if (matchesForCity) {
		results.push({
			metroAreaName: matchesForCity.metroAreaName,
			divergence: data.divergence
		})
	}
})

fs.writeFile("../outputs/divergenceData.json", JSON.stringify(results), err => {
	if (err) {
		console.error(err)
	}
})
